### ISSUE TITLE
Unable to handle null value in json input

### ISSUE THREAD

**Issue by kstenbaek** [chrismalek/jsontoxml-cli#1]
Hi Chris

I used your code with great success, a nice little tool, so thanks for that.

Just a heads-up that I noticed it does not handle null values well, for example the input:
`{
  "toplevel": [
    {
      "val1": "123",
      "val2": "321",
      "properties": {
        "prop1": "a",
        "prop2": null,
        "prop3": "c"
      }
    }
  ]
}`

returns the invalid (xml wise) output below:

`<root><toplevel><properties><prop1>a</prop1><prop2<prop3>c</prop3></properties><val1>123</val1><val2>321</val2></toplevel></root>`

best regards
kstenbaek

**Comment by dechamps** [comment]
Same here.

**Comment by dechamps** [comment]
Same here:

```
$ go run jsontoxml.go 'null'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x4c738a]

goroutine 1 [running]:
github.com/clbanning/anyxml.Xml(0x0, 0x0, 0xc420057e98, 0x1, 0x1, 0x0, 0x0, 0x43f057, 0xc4200140e4, 0x4)
	/home/e-t172/go/src/github.com/clbanning/anyxml/anyxml.go:57 +0x6a
main.convertJSONToXML(0xc4200140e0, 0x4, 0x8, 0xc4200140e0, 0x4, 0x8, 0x0, 0x0)
	/home/e-t172/dev/jsontoxml-cli/jsontoxml.go:49 +0x26c
main.main()
	/home/e-t172/dev/jsontoxml-cli/jsontoxml.go:26 +0x91
exit status 2
```

```
$ go run jsontoxml.go '{"toplevel": null}'
<root><toplevel</root>
```

**Comment by chrismalek** [comment]
I just pushed some changes that should address this. Grab the latest.
